- id: '1566066851941'
  alias: Away
  trigger:
  - entity_id: person.jochem
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.radiator_woonkamer_off
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: media_player.chromebitch
    service: media_player.turn_off
  - data:
      entity_id: switch.onkyo
    service: switch.turn_off
  - data:
      entity_id: group.all_switches
    service: switch.turn_off

- alias: Home (avond)
  trigger:
  - entity_id: person.jochem
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    state: below_horizon
    entity_id: sun.sun
  action:
  - service: script.scene_avond
  - service: script.spotify2chromecast
  - service: script.radiator_woonkamer_on
  id: e53a8b9a452d4a5f9f8cc2fbbd948681

- id: '1566071067769'
  alias: Avond
  trigger:
  - event: sunset
    offset: -00:07:00
    platform: sun
  condition:
  - condition: state
    entity_id: person.jochem
    state: home
  action:
  - service: script.scene_avond

- alias: Webhook Call Service
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: !secret webhook_generic
  action:
    service_template: '{{ trigger.json.service }}'
    data_template:
      entity_id: '{{ trigger.json.entity_id }}'
  id: 0b5c58ac9553406fb82637c0285449cb

- id: '1566074829768'
  alias: Tasker Alles uit
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_uit
  condition: []
  action:
  - service: script.scene_uit
  - data:
      entity_id: media_player.chromebitch
    service: media_player.turn_off
  - data:
      entity_id: switch.onkyo
    service: switch.turn_off
  - service: script.radiator_woonkamer_off

- id: '1568405264320'
  alias: Tasker Keuken Werk toggle
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_keukenwerktoggle
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.keuken_werk
    service: light.toggle

- id: '1568405354120'
  alias: Tasker Woonkamer plafond toggle
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_woonkamerplafondtoggle
  condition: []
  action:
  - data:
      entity_id: switch.woonkamer_plafond
    service: switch.toggle

- id: '1568406229777'
  alias: Tasker Radio toggle
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_radiotoggle
  condition: []
  action:
  - data: {}
    service: script.concertzender

- id: 'tasker_sceneoverdag'
  alias: Tasker Scene Overdag
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_sceneoverdag
  action:
  - service: script.scene_overdag

- id: 'tasker_sceneavond'
  alias: Tasker Scene Avond
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_sceneavond
  action:
  - service: script.scene_avond

- id: 'tasker_sceneavond2'
  alias: Tasker Scene Avond2
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_sceneavond2
  action:
  - service: script.scene_avond2
    
- id: 'tasker_scenerelax'
  alias: Tasker Scene Relax
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_scenerelax
  action:
  - service: script.scene_relax

- id: 'tasker_scenenachtlicht'
  alias: Tasker Scene Nachtlicht
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_scenenachtlicht
  action:
  - service: script.scene_nachtlicht

- id: 'tasker_nachtlicht'
  alias: Tasker Nachtlicht
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_nachtlicht
  condition:
  - condition: state
    state: 'off'
    entity_id: group.all_lights
  action:
  - service: script.scene_nachtlicht
    
- id: 'tasker_radiatoruit'
  alias: Tasker Radiator uit
  trigger:
  - platform: webhook
    webhook_id: !secret webhook_tasker_radiatoruit
  action:
  - service: script.radiator_woonkamer_off
      
- id: '1566142801325'
  alias: Home (dag)
  trigger:
  - entity_id: person.jochem
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    state: above_horizon
    entity_id: sun.sun
  action:
  - service: script.scene_overdag
  - service: script.spotify2chromecast
  - service: script.radiator_woonkamer_on

- alias: Wake-up light
  trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: person.jochem
    state: home
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: light.turn_on
    entity_id: group.wakeup_lights
    data:
      brightness: 0
  - service: light.turn_on
    entity_id: group.wakeup_lights
    data:
      transition: 1800
      brightness: 240
  - delay: 00:15:00
  - service: script.concertzender
  - service: python_script.volume_transition
    data:
      entity_id: media_player.chromebitch
      transition_duration: 900
      sleep_delay: 3
      start_level: 0.01
      end_level: 0.5
  id: 47d31d79b0e1410b8c4f5cb311dc92dd

- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.zigbee2mqtt_log_level
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
      topic: zigbee2mqtt/bridge/config/log_level
  id: 6b75adc07fef47a4818a22b47fed6015

- id: zigbee_join_enabled
  alias: Zigbee Join Enabled
  #hide_entity: true
  trigger:
    platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: 'on'
  action:
    service: timer.start
    entity_id: timer.zigbee_permit_join

- id: zigbee_join_disabled
  alias: Zigbee Join Disabled
  #hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  - platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: 'off'
  action:
  - service: timer.cancel
    data:
      entity_id: timer.zigbee_permit_join
  - service: switch.turn_off
    entity_id: switch.zigbee2mqtt_main_join

- id: Plafondlamp_bij_donker_lx
  alias: Plafondlamp aan als het donker is (lx)
  trigger:
    platform: numeric_state
    entity_id: sensor.bewegingsmelder_illuminance
    below: 60
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.keuken_werk
      state: 'on'
    - condition: state
      entity_id: switch.woonkamer_plafond
      state: 'off'
      for: '00:15:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.av_meubel
        state: 'off'
      - condition: state
        entity_id: switch.av_tafellamp
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.woonkamer_plafond

#- id: Plafondlamp_bij_donker_occupancy
#  alias: Plafondlamp aan als het donker is (occ)
#  trigger:
#    platform: state
#    entity_id: binary_sensor.bewegingsmelder_occupancy
#    from: 'off'
#    to: 'on'
#  condition:
#    condition: and
#    conditions:
#    - condition: state
#      entity_id: light.keuken_werk
#      state: 'on'
#    - condition: state
#      entity_id: switch.woonkamer_plafond
#      state: 'off'
#      for: '00:15:00'
#    - condition: numeric_state
#      entity_id: sensor.bewegingsmelder_illuminance
#      below: 60
#    - condition: or
#      conditions:
#      - condition: state
#        entity_id: light.av_meubel
#        state: 'off'
#      - condition: state
#        entity_id: switch.av_tafellamp
#        state: 'off'
#  action:
#  - service: switch.turn_on
#    entity_id: switch.woonkamer_plafond
#
- id: Plafondlamp_bij_donker_keukenwerk
  alias: Plafondlamp aan als keukenwerk aan gaat en het donker is
  trigger:
    platform: state
    entity_id: light.keuken_werk
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.bewegingsmelder_illuminance
      below: 60
    - condition: or
      conditions:
      - condition: state
        entity_id: light.av_meubel
        state: 'off'
      - condition: state
        entity_id: switch.av_tafellamp
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.woonkamer_plafond

- id: Plafondlamp_bij_licht_lx
  alias: Plafondlamp uit als het te licht is
  trigger:
    platform: numeric_state
    entity_id: sensor.bewegingsmelder_illuminance
    above: 60
  condition:
  - condition: state
    entity_id: switch.woonkamer_plafond
    state: 'on'
    for: '00:15:00'
  action:
  - service: switch.turn_off
    entity_id: switch.woonkamer_plafond

- id: onkyo_start_playing
  alias: Zet onkyo aan als Chromebitch afspeelt
  trigger:
    platform: state
    entity_id: media_player.chromebitch
    to: 'playing'
  condition:
  - condition: state
    state: 'off'
    entity_id: switch.onkyo
  action:
  - service: switch.turn_on
    entity_id: switch.onkyo

#- id: onkyo_stop_playing_delay_timer
#  alias: Start timer voor dat Onkyo definitief uit gaat
#  trigger:
#    platform: state
#    entity_id: media_player.chromebitch
#    to: 'off'
#  action:
#    service: timer.start
#    entity_id: timer.onkyo

#- id: onkyo_stop_playing
#  alias: Zet onkyo uit als Chromebitch uit gaat
#  trigger:
#    platform: event
#    event_type: timer.finished
#    event_data:
#      entity_id: timer.onkyo
#  condition:
#  - condition: state
#    state: 'off'
#    entity_id: media_player.chromebitch
#  action:
#  - service: switch.turn_off
#    entity_id: switch.onkyo

- id: onkyo_stop_playing
  alias: Zet onkyo uit als Chromebitch uit gaat
  trigger:
    platform: state
    entity_id: media_player.chromebitch
    to: 'off'
  action:
  - delay: 00:00:17
  - condition: state
    state: 'off'
    entity_id: media_player.chromebitch
  - service: switch.turn_off
    entity_id: switch.onkyo

- id: radiator_woonkamer_on
  alias: Switch Radiator in Woonkamer on
  trigger:
    platform: state
    entity_id: input_boolean.radiator_woonkamer
    to: 'on'
  action:
  - service: script.radiator_woonkamer_on
  
- id: radiator_woonkamer_off
  alias: Switch Radiator in Woonkamer off
  trigger:
    platform: state
    entity_id: input_boolean.radiator_woonkamer
    to: 'off'
  action:
  - service: script.radiator_woonkamer_off

- id: radiator_woonkamer_max_on
  alias: Switch Radiator in Woonkamer Max on
  trigger:
    platform: state
    entity_id: input_boolean.radiator_woonkamer_max
    to: 'on'
  action:
  - service: script.radiator_woonkamer_max_on

- id: spotifylaptop2chromebitch
  alias: Speel muziek van laptop op Chromcast
  trigger:
    platform: state
    entity_id: media_player.spotify_jochem_van_leeuwen
    to: playing
#  condition:
#  - condition: state
#    entity_id: person.jochem
#    state: home
#  - condition: template
#    value_template: "{{ is_state_attr('media_player.spotify_jochem_van_leeuwen', 'source', 'HI-LAPTOP-JLN1') }}" 
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.jochem
      state: home
    - condition: or
      conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.spotify_jochem_van_leeuwen', 'source', 'HI-LAPTOP-JLN1') }}" 
      - condition: template
        value_template: "{{ is_state_attr('media_player.spotify_jochem_van_leeuwen', 'source', 'DESKTOP-56IBQA7') }}" 
  action:
  - service: script.spotify2chromecast
  
- id: to_tasker_radiatoruit
  alias: Stuur bericht radiatoruit naar tasker
  trigger:
    platform: time
    at: '21:45:00'
  condition:
  - condition: state
    entity_id: input_boolean.radiator_woonkamer
    state: 'on'
  action:
  - service: script.to_tasker_radiatoruit
  
- id: radiator_aan_als_thuis
  alias: Zet radiator aan als ik om 9:05 nog thuis ben
  trigger:
    platform: time
    at: '09:05:00'
  condition:
  - condition: state
    entity_id: input_boolean.radiator_woonkamer
    state: 'off'
  - condition: state
    entity_id: person.jochem
    state: home
  action:
  - service: script.radiator_woonkamer_on