
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info
  logs:
    homeassistant.components.http.ban: warning
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: https://hass.troep.net
  use_x_forwarded_for: true
  trusted_proxies: 185.107.213.176
  
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes
light: !include lights.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
python_script: !include_dir_list python_scripts
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

frontend:
  themes: !include_dir_merge_named themes

mqtt:
  discovery: true
  broker: localhost
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

#hdmi_cec:
#  devices:
#    5: Onkyo

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
    
spotify:
  client_id: !secret spotify_api_client_id
  client_secret: !secret spotify_api_client_secret

hacs:
  token: !secret hacs_token
  sidepanel_title: HACS
  appdaemon: True
  python_script: True
  theme: True

shell_command:
  get_url: curl -X GET '{{ url }}'
    
# ZIGBEE2MQTT    
# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

# Input text to input Zigbee2mqtt friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2mqtt Old Name
  zigbee2mqtt_new_name:
    name: Zigbee2mqtt New Name
  zigbee2mqtt_remove:
    name: Zigbee2mqtt Remove

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120
# /ZIGBEE2MQTT    

#timer voor deurnotificatie
  voordeur:
    name: Voordeur delay
    duration: '00:00:45'
